= Awkward Array Specification (1.0-pre1)
:Author: Jim Pivarski
:Email: pivarski@princeton.edu
:Date: 1.0 expected early 2019
:Revision: 1.0-pre1
:toc:

== Introduction

Array programming is a general programming paradigm, similar to functional programming or object-oriented programming in its scope. Pioneered by APL in 1962, this paradigm has appeared primarily in interactive data processing languages aimed at data analysts and statisticians: S (1976), MATLAB (1984), S-PLUS (1988), R (1993), and Numpy (2005). Unlike its predecessors, Numpy is not a language in itself, but a foundational library for science and statistics in Python.

Array programming is mostly used on problems with regular, rectangular grids. It is possible to represent and operate on more complex data structures, but it is considerably more awkward to do so in current frameworks. Fortunately, this awkwardness may be hidden in a suite of higher-level array classes that present modest extensions of the array programming paradigm to the user.

https://github.com/scikit-hep/awkward-array[awkward-array] (https://pypi.org/project/awkward[awkward] on PyPI) is an implementation of complex data structures and operations in Python, depending only on https://pandas.pydata.org[Numpy]. Drop-in replacements optimized with compiled code or leveraging GPUs are foreseen, though they would present the same user interface. Extensions for using awkward-array as https://pandas.pydata.org[Pandas] columns, in https://pandas.pydata.org[Numba]-compiled functions, and in distributed calculations with https://pandas.pydata.org[Dask] are also foreseen. These arrays can already be persisted and reconstituted in any data format supporting Numpy arrays, such as HDF5, or named binary blobs, such as ZIP or key-value stores.

=== This specification

Despite awkward-array's focus on Python and Numpy, the data model it represents is language-agnostic. This document describes awkward-array as a protocol for generalizing array programming to complex structures in any environment. It is a normative document in the sense that it describes what awkward-array in Python _should_ do; discrepancies between this document and the Python implementation would usually be decided in favor of the document (though the document itself may have "`bugs`" to be fixed in a later version). It is also normative in the sense that other implementations, in C++ or MATLAB for instance, that claim to "`adhere to the awkward-array specification`" _should_ also behave as described here.

The goal of this document is to describe an extended array programming interface in terms of a "`least common denominator`" array programming interface. For simplicity, we will use Python syntax and Numpy function names, but a library in a different language or based on a different array library may still adhere to the awkward-array specification by providing a translation of these idioms.

It is not a goal of this document to explain how the awkward-array features are implemented. Drop-in replacements for the Numpy-only awkward-array library and libraries in other environments are free to implement the specification differently. They will thus have different performance characteristics. This specification cannot provide any performance hints.

Documentation is not an explicit goal of this specification, though users may read it to learn how to use any compliant implementation. Unlike documentation, however, this document describes what an awkward-array library should do, not necessarily what it does. Users are encouraged to file https://github.com/scikit-hep/awkward-array/issues[issues here] if a discrepancy is found in the Numpy-only implementation.

The major and minor version numbers of this specification, `xx.yy`, correspond to the major and minor version numbers of the Numpy-only implementation: `xx.yy` in `xx.yy.zz`. The revision number, `zz`, increases as it strives toward compliance with the specification. This particular version of the document is a pre-release; compliance is only required for released specifications.

A library may implement more features than those described in this specification without affecting its compliance. If it implements fewer classes or fewer methods, it can only be said to be "`partially compliant,`" and would have to enumerate the missing classes or methods.

=== Least common denominator array protocol

Necessary features of the underlying array library are described in this section (a) to establish a syntax used in the rest of this document and (b) as a basis for translating idioms of non-Numpy libraries into the language of this document. For instance, another language may use a function to extract slices of an array, rather than Python's `array[start:stop:step]` syntax. If so, the awkward-array idiom in that language would use the same function name and arguments, rather than the Python ones.

The underlying array library must have the following features.

  * It must be able to represent sequences of primitive values, known as arrays. An array is homogeneous: all values in an array have the same type. Primitive types include integers, floating point numbers, and boolean (true/false) values. An awkward-array library inherits the primitives of the underlying library -- if a base array library doesn't support complex numbers, then neither does its awkward-array extension. Arrays need not be contiguous in memory, though this is the simplest case.
  * Arrays may be _N_-dimensional.






== Features provided by an awkward-array library


=== High-level types


=== Low-level structures


== General properties of all array classes


== Jaggedness


=== JaggedArray


=== ByteJaggedArray


== Product types


=== Table


== Sum types


=== UnionArray


== Objects


=== Mix-in Methods


=== ObjectArray


=== StringArray


== Masking


=== MaskedArray


=== BitMaskedArray


=== IndexedMaskedArray


== Indirection


=== IndexedArray


=== ByteIndexedArray


=== SparseArray


== Non-contiguousness


=== ChunkedArray


=== AppendableArray


== Lazy-loading


=== VirtualArray


== Methods defined on all arrays


== Serialization
