= Awkward Array Specification (1.0-pre1)
:Author: Jim Pivarski
:Email: pivarski@princeton.edu
:Date: 1.0 expected early 2019
:Revision: 1.0-pre1
:toc:

== Introduction

Array programming is a general programming paradigm, similar to functional programming or object-oriented programming in its scope. Pioneered by APL in 1962, this paradigm has appeared primarily in interactive data processing languages aimed at data analysts and statisticians: S (1976), MATLAB (1984), S-PLUS (1988), R (1993), and Numpy (2005). Unlike its predecessors, Numpy is not a language in itself, but a foundational library for science and statistics in Python.

Array programming is mostly used on problems with regular, rectangular grids. It is possible to represent and operate on more complex data structures, but it is considerably more awkward to do so in current frameworks. Fortunately, this awkwardness may be hidden in a suite of higher-level array classes that present modest extensions of the array programming paradigm to the user.

https://github.com/scikit-hep/awkward-array[awkward-array] (https://pypi.org/project/awkward[awkward] on PyPI) is an implementation of complex data structures and operations in Python, depending only on https://pandas.pydata.org[Numpy]. Drop-in replacements optimized with compiled code or leveraging GPUs are foreseen, though they would present the same user interface. Extensions for using awkward-array as https://pandas.pydata.org[Pandas] columns, in https://pandas.pydata.org[Numba]-compiled functions, and in distributed calculations with https://pandas.pydata.org[Dask] are also foreseen. These arrays can already be persisted and reconstituted in any data format supporting Numpy arrays, such as HDF5, or named binary blobs, such as ZIP.

=== This specification

Despite awkward-array's focus on Python and Numpy, the data model it represents is language-agnostic. This document describes awkward-array as a protocol for generalizing array programming to complex structures in any environment. It is a normative document in the sense that it describes what awkward-array in Python _should_ do; discrepancies between this document and the Python implementation would usually be decided in favor of the document (though the document itself may have "`bugs`" to be fixed in a later version). It is also normative in the sense that other implementations, in C++ or MATLAB for instance, that claim to "`adhere to the awkward-array specification`" _should_ also behave as described here.

The goal of this document is to describe an extended array programming interface in terms of a "`least common denominator`" array programming interface. For simplicity, we will use Python syntax and Numpy function names, but a library in a different language or based on a different array library may still adhere to the awkward-array specification by providing a translation of the idioms.

It is not a goal of this document to explain how these features are implemented. Drop-in replacements for the Numpy-only awkward-array library and libraries in other environments are free to implement the specification differently. They will thus have different performance characteristics. This specification also cannot provide any performance hints.

Documentation is not an explicit goal of this specification, though it may be read to learn the library. Unlike documentation, however, this document describes what an awkward-array library should do, not necessarily what it does. Users are encouraged to file issues if a discrepancy is found.

The major and minor version number of this document, `xx.yy`, correspond to the major and minor version number of the Numpy-only awkward-array library: `xx.yy` in `xx.yy.zz`. The implementation's revision number, `zz`, increases as it strives toward compliance with the specification.

=== Least common denominator array protocol





== Features provided by an awkward-array library


=== High-level types


=== Low-level structures


== General properties of all array classes


== Jaggedness


=== JaggedArray


=== ByteJaggedArray


== Product types


=== Table


== Sum types


=== UnionArray


== Objects


=== Mix-in Methods


=== ObjectArray


=== StringArray


== Masking


=== MaskedArray


=== BitMaskedArray


=== IndexedMaskedArray


== Indirection


=== IndexedArray


=== ByteIndexedArray


=== SparseArray


== Non-contiguousness


=== ChunkedArray


=== AppendableArray


== Lazy-loading


=== VirtualArray


== Methods defined on all arrays


== Serialization
